name: Build
on:
  - pull_request
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        id: dependency-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn example install

      - name: Build Example App
        working-directory: example/android
        run: ./gradlew build

  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        id: dependency-cache
        with:
          path: |
            **/node_modules
            example/ios/Pods
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn example install
          yarn pods

      - uses: actions/cache@v2
        id: derived-data-cache
        with:
          path: derivedData
          key: ${{ runner.os }}-build-derived-data-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-build-derived-data-

      - name: Build Example App
        working-directory: example
        run: |
          xcodebuild -workspace ios/McuManagerExample.xcworkspace \
            -scheme McuManagerExample \
            -configuration Debug \
            -IgnoreFileSystemDeviceInodeChanges=YES \
            -derivedDataPath derivedData \
            -sdk iphonesimulator | xcpretty
