name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: 11
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Typecheck MCU Manager
        run: pnpm typecheck
        working-directory: ./react-native-mcu-manager

      - name: Typecheck Example
        run: pnpm typecheck
        working-directory: ./example
